### ISSUE TITLE
Optimize method DesSer<T> with json_serializable

### ISSUE THREAD

**Issue by jackyhieu1211-hn** [bartektartanus/pref_dessert#6]
Hi every one.
I optimized method DesSer<T> with [json_serializable.](https://pub.dev/packages/json_serializable). I show code below. Hope.It will help you.

Step 1: import library  [json_serializable.](https://pub.dev/packages/json_serializable) in _pubspec.yaml_

```
dependencies:
  flutter:
    sdk: flutter
  pref_dessert: ^0.4.0+1
  json_serializable: ^3.2.2
  cupertino_icons: ^0.1.2
  json_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
```

Step 2:  Create User class

```
import 'package:pref_dessert/pref_dessert.dart';
import 'package:timesheet/utils/constants.dart';
import 'package:json_annotation/json_annotation.dart';

part 'user.g.dart';

@JsonSerializable()
class User {
  var uid = "";
  var photoUrl = "";
  var displayName = "";
  var email = "";

  User({this.uid, this.photoUrl, this.displayName, this.email});
}

class UserDesSer extends JsonDesSer<User> {
  @override
  String get key => PREF_USER;

  @override
  User fromMap(Map<String, dynamic> map) => _$UserFromJson(map);

  @override
  Map<String, dynamic> toMap(User user) => _$UserToJson(user);
}

```

Step 3: Run command :  `flutter pub run build_runner build`
